### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tejt99** [jimkang/word-syllable-map#1]
Hello, I have never used nodejs before so if this is noobish, don't hesitate to say. But when I ran it just as you said, once the database is setup, I recieved this when the second block of code ran: `err: IO error: lock /app/base.db/LOCK: already held by process`. Please help as this is just what I am looking for.

**Comment by tejt99** [comment]
You can view the error here: [https://runkit.com/tejt99/5edfd11ec2e7c8001ad5eeca](https://runkit.com/tejt99/5edfd11ec2e7c8001ad5eeca)

**Comment by jimkang** [comment]
Are you sure the build is done? Did you get the `Successfully set up database.` message?

Once you do that, you don't need to run the setup code anymore.

**Comment by tejt99** [comment]
Hi thanks for the quick reply, if the first block isn't there, then I recieve a `err: Key not found in database [HELLO]`.

**Comment by jimkang** [comment]
Did you actually see the message I mentioned, though?

**Comment by tejt99** [comment]
Yes

**Comment by jimkang** [comment]
Is `base.db` actually populated? Can you go into your `base.db` directory to see if files are actually there?

**Comment by tejt99** [comment]
I don't believe I can view it as it's runkit and my pc can't run node.

**Comment by tejt99** [comment]
Sorry for the unclarity, I updated the comment.

**Comment by jimkang** [comment]
Oh, sorry. It's not going to work on Runkit. You need to run it on a computer with persistent storage.
